---
name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6

    - name: Install Valgrind
      run: |
        apt-get install valgrind

    - name: Build
      run: |
        make build-test

    - name: Tests
      run: |
        make valgrind TEST_FLAGS=--color=always
